version: '3'

services:
  data:
    build: ./datos
    volumes:
      - ./datos:/servicio/datos
  web:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - data
    volumes:
      - /tmp:/servicio/datos
    
volumes: 
    data:
